import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const p = await b.newPage({ viewport: { width: 1100, height: 950 } })
const errs = []
p.on('pageerror', e => errs.push(e.message))
await p.goto('file:///home/claude/gastos-en-casa.html')
const i = p.locator('input')
await i.nth(0).fill('Uno'); await i.nth(1).fill('Dos')
await p.getByRole('button', { name: 'Seguir' }).click()
await p.getByRole('button', { name: 'Empezar' }).click()
await p.waitForTimeout(500)
await p.locator('aside button').filter({ hasText: 'Ajustes' }).first().click()
await p.waitForTimeout(500)
const aviso = await p.locator('text=/archivo suelto/').first().textContent().catch(() => null)
const hayBoton = await p.getByRole('button', { name: /Activar sincronización/ }).count()
console.log('aviso mostrado:', aviso ? 'SÍ — "' + aviso.trim().slice(0, 60) + '…"' : 'NO')
console.log('botón de activar oculto:', hayBoton === 0 ? 'SÍ' : 'NO (sigue visible)')
await p.locator('text=/Sincronización con tu pareja/').scrollIntoViewIfNeeded()
await p.waitForTimeout(300)
await p.screenshot({ path: 'shots/guard.png' })
console.log('errores:', errs.length)
await b.close()
