import { chromium } from 'playwright'
import path from 'node:path'; import fs from 'node:fs'; import http from 'node:http'
import { fileURLToPath } from 'node:url'
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const dist = path.join(root, 'dist')
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json'}
const server=http.createServer((q,r)=>{let p=decodeURIComponent(q.url.split('?')[0]);if(p==='/')p='/index.html'
 const f=path.join(dist,p);if(!fs.existsSync(f)||fs.statSync(f).isDirectory()){r.writeHead(404);return r.end()}
 r.writeHead(200,{'Content-Type':MIME[path.extname(f)]??'application/octet-stream'});fs.createReadStream(f).pipe(r)})
await new Promise(r=>server.listen(4175,r))
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const p = await b.newPage({ viewport:{width:1150,height:950}, locale:'es-ES' })
const errs=[]; p.on('pageerror',e=>errs.push(e.message)); p.on('console',m=>m.type()==='error'&&errs.push(m.text()))
await p.goto('http://localhost:4175/')
const i = p.locator('input')
await i.nth(0).fill('Uno'); await i.nth(1).fill('Dos')
await p.getByRole('button',{name:'Seguir'}).click()
await p.locator('input[type=month]').fill('2026-08')
await p.getByRole('button',{name:'Empezar'}).click()
await p.waitForTimeout(500)
await p.locator('aside button').filter({hasText:'Gastos'}).first().click()
await p.waitForTimeout(400)
await p.getByRole('button',{name:'+ A mano'}).click()
await p.waitForTimeout(400)
await p.getByRole('button',{name:'Ingreso',exact:true}).click()
await p.waitForTimeout(300)
await p.locator('.fixed input[type=text], .relative input').first().fill('Sueldo')
await p.locator('input[type=date]').fill('2026-08-01')
// elegir la cuenta donde entró
const selCuenta = p.locator('.fixed select').first()
const ops = await selCuenta.locator('option').evaluateAll(o=>o.map(x=>({v:x.value,t:x.textContent})))
console.log('cuentas ofrecidas:', ops.map(o=>o.t).join(' | '))
const lhv = ops.find(o=>o.v && /LHV/.test(o.t))
if (lhv) await selCuenta.selectOption(lhv.v)
await p.waitForTimeout(300)
await p.locator('input[inputmode=decimal]').fill('2764.47')
const notas = p.locator('input[placeholder*="excepción"]')
if (await notas.count()) await notas.fill('Cobrado el 31/07 por excepción')
await p.waitForTimeout(300)
await p.screenshot({path:'shots/manual-dialogo.png'})
await p.getByRole('button',{name:'Guardar'}).click()
await p.waitForTimeout(800)
const chip = await p.locator('text=/a mano/').first().count()
const ing = await p.locator('li').filter({hasText:'Sueldo'}).first().textContent().catch(()=>null)
console.log('etiqueta "a mano" visible:', chip>0?'SÍ':'NO')
console.log('fila:', (ing||'').replace(/\s+/g,' ').slice(0,90))
await p.locator('aside button').filter({hasText:'Inicio'}).first().click()
await p.waitForTimeout(600)
const entro = await p.locator('text=Entró').locator('..').textContent().catch(()=>null)
console.log('en Inicio →', (entro||'').replace(/\s+/g,' ').slice(0,60))
await p.screenshot({path:'shots/manual-inicio.png'})
console.log('errores:', errs.length)
await b.close(); server.close()
